run:
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 30s

  # Exit code when at least one issue was found.
  issues-exit-code: 2

  # Include test files or not.
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.19'

output:
  # Sort results by: filepath, line and column.
  sort-results: true

linters:
  # Enabling all linters.
  enable-all: true
