run:
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 30s

  # Exit code when at least one issue was found.
  issues-exit-code: 2
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.20'

output:
  # Sort results by: filepath, line and column.
  sort-results: true

linters:
  # Enabling all linters.
  enable-all: true

  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - varnamelen
    - nlreturn
    - wsl
